# printWidth: 80 # 80
# tabWidth: 2 # 2
# useTabs: false # false
semi: false # false
singleQuote: true # false
# trailingComma: none # none | es5 | all
# jsxBracketSameLine: false # false
# arrowParens: avoid # avoid | always
useTabs: true #true
trailingComma: none #none
bracketSpacing: true #true
jsxBracketSameLine: true #true
